### ISSUE TITLE
zabbix.service_weight' doesn't exist

### ISSUE THREAD

**Issue by andreaconsadori** [rodrigofns/zabbix-service-tree#5]
[root@zabbix service-tree-daemon]# php trapdaemon.php
2014-07-15 14:34:31 Updating tree.
2014-07-15 14:34:31 100100000000006 (Wifi Urbano) on ProcessNode.
2014-07-15 14:34:31   100100000000007 (HotspotBrescia) on ProcessNode.
2014-07-15 14:34:31     100100000000008 (Adsl1) on ProcessNode.
2014-07-15 14:34:31     100100000000008 is a leaf node.
PHP Fatal error:  Uncaught exception 'Exception' with message 'SQL ERROR:

```
            SELECT *
            FROM service_weight
            WHERE idservice = ?
```

42S02 Table 'zabbix.service_weight' doesn't exist' in /usr/share/zabbix/extras/service-tree-daemon/Database.class.php:46
Stack trace:
#0 /usr/share/zabbix/extras/service-tree-daemon/trapdaemon.php(65): Database->query('???SELECT *???F...', '100100000000008')
#1 /usr/share/zabbix/extras/service-tree-daemon/trapdaemon.php(103): GetWeightOfStatus(Object(Database), '100100000000008', '0', 2)
#2 /usr/share/zabbix/extras/service-tree-daemon/trapdaemon.php(90): ProcessNode(Object(Database), '100100000000008', 'Adsl1', '0', 2)
#3 /usr/share/zabbix/extras/service-tree-daemon/trapdaemon.php(90): ProcessNode(Object(Database), '100100000000007', 'HotspotBrescia', '0', 1)
#4 /usr/share/zabbix/extras/service-tree-daemon/trapdaemon.php(125): ProcessNode(Object(Database), '100100000000006', 'Wifi Urbano', '0')
#5 /usr/share/zabbix/extras/service-tree-daemon/trapdaemon.php(138): UpdateServiceTree(Object(Database)) in /usr/share/zabbix/extras/service-tree-daemon/Database.class.php on line 46

**Comment by andreaconsadori** [comment]
![errore1](https://cloud.githubusercontent.com/assets/1265395/3584698/21b8ec48-0c1d-11e4-9d6c-bd2d948f7f87.JPG)
 and this is my confg

[root@zabbix service-tree-daemon]# cat __conf.php
<?php

// This constant appears undefined in some Zabbix instances, so let's use the hammer.
if(!defined('IMAGE_FORMAT_PNG'))
        define('IMAGE_FORMAT_PNG', 'PNG');

// The whole system loads the settings from the Zabbix
// configurations indicated below.

// Don't forget to set log_errors=On in php.ini .
// Log is likely to be stored in /var/log/apache2/error.log .

#$ZABBIX_CONF = '/rede/www/zabbix-2.0.2-masternode/conf/zabbix.conf.php';
$ZABBIX_CONF = '/etc/zabbix/web/zabbix.conf.php';
$ZABBIX_API = 'http://localhost/zabbix/zabbix-2.0.2-masternode';
